version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_IMAGE_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      - internal_network

  ui:
    image: ${USER_NAME}/ui:${UI_IMAGE_VERSION}
    ports:
      - ${PUMA_PORT}:${PUMA_PORT}/tcp
    networks:
      - external_network
      - internal_network

  post:
    image: ${USER_NAME}/post:${POST_IMAGE_VERSION}
    networks:
      - internal_network

  comment:
    image: ${USER_NAME}/comment:${COMMENT_IMAGE_VERSION}
    networks:
      - internal_network

  alertmanager:
    image: ${USER_NAME}/alertmanager
    networks:
      - internal_network
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - 9093:9093

volumes:
  post_db:
  prometheus_data:

networks:
  internal_network:
    external: false
  external_network:
    external: true
