version: '3.3'
services:
  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - '9090:9090'
    networks:
      - internal_network
      - external_network
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'

  node_exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    networks:
      - internal_network
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

  mongodb_exporter:
    image: bitnami/mongodb-exporter:${MONGO_EXPORTER_VERSION}
    networks:
      - internal_network
    environment:
      MONGODB_URI: "mongodb://post_db:27017"

  cloudprober_exporter:
    image: ${USER_NAME}/cloudprober
    networks:
      - internal_network

  cadvisor:
    image: google/cadvisor:v0.29.0
    networks:
      - internal_network
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'

  grafana:
    image: grafana/grafana:5.0.0
    networks:
      - internal_network
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - 3000:3000

  telegraf:
    image: ${USER_NAME}/telegraf
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - internal_network

  influxdb:
    image: influxdb
    volumes:
      - 'influxdb_data:/var/lib/influxdb'
    networks:
      - internal_network

volumes:
  post_db:
  prometheus_data:
  grafana_data:

networks:
  internal_network:
    external: false
  external_network:
    external: true
