version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_IMAGE_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post_db

  comment_db:
    image: mongo:${MONGO_IMAGE_VERSION}
    volumes:
      - comment_db:/data/db
    networks:
      - back_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.comment_db

  ui:
    image: ${USER_NAME}/ui:${UI_IMAGE_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - ${PUMA_PORT}:${PUMA_PORT}/tcp
    networks:
      - front_net
      - back_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    image: ${USER_NAME}/post:${POST_IMAGE_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - back_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    image: ${USER_NAME}/comment:${COMMENT_IMAGE_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - back_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.comment

volumes:
  post_db:
  comment_db:

networks:
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
