version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_IMAGE_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      - reddit
  ui:
    image: ${USERNAME}/ui:${UI_IMAGE_VERSION}
    ports:
      - ${PUMA_PORT}:${PUMA_PORT}/tcp
    networks:
      - reddit
  post:
    image: ${USERNAME}/post:${POST_IMAGE_VERSION}
    networks:
      - reddit
  comment:
    image: ${USERNAME}/comment:${COMMENT_IMAGE_VERSION}
    networks:
      - reddit

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    networks:
      - reddit
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'

volumes:
  post_db:
  prometheus_data:

networks:
  reddit:
