version: '3.3'
services:
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    networks:
      - internal_network
      - external_network
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'

  node_exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    networks:
      - internal_network
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

  mongodb_exporter:
    image: bitnami/mongodb-exporter:${MONGO_EXPORTER_VERSION}
    networks:
      - internal_network
    environment:
      MONGODB_URI: "mongodb://post_db:27017"

  cloudprober_exporter:
    image: ${USERNAME}/cloudprober_exporter
    networks:
      - internal_network

  cadvisor:
    image: google/cadvisor:v0.29.0
    networks:
      - internal_network
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'

volumes:
  post_db:
  prometheus_data:

networks:
  internal_network:
    external: false
  external_network:
    external: true
