---
plugin: gcp_compute
zones:
  - europe-north1-a
projects:
  - docker-267311
filters: []
auth_kind: serviceaccount
service_account_file: ~/docker-267311-9a47c505e6da.json
scopes:
  - 'https://www.googleapis.com/auth/compute.readonly'
groups:
  app: "'app' in name"
hostnames:
  - name
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
...
